### ISSUE TITLE
`[参考]` in data_index.js causes several issues

### ISSUE THREAD

**Issue by Ragnar-F** [autohotkey-docs-translation/v2-ja#4]
`[参考]` exists in several places, but specifically `[参考] ["^","Variables.htm#bitwise",4],` located in docs/static/source/data_index.js prevents the index from functioning correctly and the search data from being up-to-date. Why is it used at all? Wouldn't it make more sense to use the Notes feature of OmegaT?

**Comment by penguinthedawn** [comment]
I'm sorry I couldn't log in for a long time. The reason is that I left the completed translation uncorrected. So, I fixed all of segment contains the word "[参考]". I'm sorry for the inconvenience, thank you.

**Comment by Ragnar-F** [comment]
All good! My aim is to publish the latest translations as error-free as possible. You can always email me (you should have my address now) if you want to decide for yourself when the new translations should be published. Otherwise, I will publish them regularly. Thanks again for your hard work 😉
